# generated by pkgs_update.exs (2022-01-15)
import
  (fetchTarball {
    name = "nixpkgs-unstable_2022-01-15";
    url = "https://github.com/NixOS/nixpkgs/archive/46821ea01c8f54d2a20f5a503809abfc605269d7.tar.gz";
  })
{ }
